---
user_config:
  monitor_with_logs: true
  monitor_with_simulator: false
  # Purge fetchMetrics documents after this time
  purge_old_docs_after_hours: 72
  polling_interval_in_secs: 10
  is_accelerated: false
cluster_details:
  # AWS launch template ID
  launch_template_id: abc
  launch_template_version: '1'
  # opensearch cluster name
  cluster_name: cluster.1
  # opensearch credentials
  os_credentials:
    os_admin_username: admin
    os_admin_password: admin
  # ssh login username & group
  os_user: ubuntu
  os_group: ubuntu
  # opensearch version
  os_version: 2.3.0
  # Default opensearch config path.
  os_home: /usr/share/opensearch
  # Domain name for opensearch nodes. It is required to configure SSL. 
  domain_name: snappyflow.com
  cloud_type: AWS
  cloud_credentials:
    secret_key: secret_key
    access_key: access_key
    pem_file_path: /usr/share/pemfile.pem
    region: us-west-2
  # Maximum number of nodes at any point in the cluster
  max_nodes_allowed: 10
  # Minimum number of nodes at any point in the cluster
  min_nodes_allowed: 3
task_details:
- task_name: scale_up_by_1
  operator: OR
  rules:
  - metric: CpuUtil
    limit: 55
    stat: AVG
    decision_period: 300
  - metric: CpuUtil
    limit: 50
    stat: COUNT
    occurrences: 10
    decision_period: 300
  - metric: RamUtil
    limit: 90
    stat: AVG
    decision_period: 300
- task_name: scale_up_by_1
  operator: EVENT
  rules:
  - scheduling_time: "0 0 * * 1-5"
    number_of_node: 6
- task_name: scale_down_by_1
  operator: EVENT
  rules:
  - scheduling_time: "0 0 * * 6-7"
    number_of_node: 3
- task_name: scale_down_by_1
  operator: AND
  rules:
  - metric: CpuUtil
    limit: 40
    stat: AVG
    decision_period: 300
  - metric: CpuUtil
    limit: 40
    stat: COUNT
    occurrences: 6
    decision_period: 300
  - metric: RamUtil
    limit: 45
    stat: AVG
    decision_period: 300
