---
  - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
    wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      search_regex: OpenSSH
      delay: 30
      timeout: 600
      sleep: 30
    connection: local

  - name: install python on ubuntu
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python3)
    register: task_result
    until: task_result.rc == 0
    retries: 5
    delay: 30

  # Commenting below check since the gather_facts:no as it throws error on new node since python is not installes. It can also not check ansible_distribution info
  # Disabling for Amazon Linux 2 as selinux is disabled by default.
  #  - name: Disable the selinux
  #    selinux:
  #      state: disabled
  #    when: (ansible_distribution != "Ubuntu") and (ansible_distribution != "Amazon")

  - name: Install ansible
    import_tasks: install_ansible.yml

  - name: Tune the system settings
    import_tasks: tune.yml
  
  - name: include opensearch installation
    include: opensearch.yml
  
  - name: include security plugin for opensearch
    include: security.yml

  - name: Populate hosts | populate inventory into hosts file
    become_user: root
    become: yes
    blockinfile:
      dest: /etc/hosts
      block: |-
        {% for item in groups['all'] %}
        {{ hostvars[item]['ansible_private_host'] }} {{ item }}.{{ domain_name }} {{ item }}
        {% endfor %}
      state: present
      create: yes
      backup: yes
      marker: "# Ansible inventory hosts {mark}"
