---

- name: OpenSearch Install | Download opensearch {{ os_version }}
  get_url:
    url: "{{ os_download_url }}/{{ os_version }}/opensearch-{{ os_version }}-linux-x64.tar.gz"
    dest: "/tmp/opensearch.tar.gz"
  register: download
  become: yes

- name: OpenSearch Install | Create opensearch user
  user:
    name: "{{ os_user }}"
    state: present
    shell: /bin/bash
  when: download.changed
  become: yes

- name: OpenSearch Install | Create home directory
  file:
    path: "{{ os_home }}"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  when: download.changed
  become: yes

- name: OpenSearch Install | Extract the tar file
  command: chdir=/tmp/ tar -xvzf opensearch.tar.gz -C "{{ os_home }}" --strip-components=1
  when: download.changed
  become: yes

- name: OpenSearch Install | Copy Configuration File
  template:
    src: "opensearch-{{ cluster_type }}.yml"
    dest: "{{os_conf_dir}}/opensearch.yml"
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
    mode: 0600
    backup: yes
  become: yes


- name: OpenSearch Install | create systemd service
  template:
    src: opensearch.service
    dest: "{{ systemctl_path }}/opensearch.service"
  become: yes


- name: Create Unicast_hosts.txt file
  become: yes
  file:
      path: "{{ os_conf_dir }}/unicast_hosts.txt"
      state: touch

- name: Update the unicast_hosts.txt file with Host IPs
  become: yes
  become_user: root
  lineinfile:
    path: "{{ os_conf_dir }}/unicast_hosts.txt"
    line: "{{ hostvars[item].ansible_private_host }}"
    state: present
  with_items:
  - "{{ groups['all'] }}"
